// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, created_at, name, email, email_confirmed, password_hash
) VALUES (
  ?, ?, ?, ?, ?, ?
) RETURNING id, created_at, name, email, email_confirmed, password_hash
`

type CreateUserParams struct {
	ID             string
	CreatedAt      int64
	Name           string
	Email          string
	EmailConfirmed bool
	PasswordHash   []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.Name,
		arg.Email,
		arg.EmailConfirmed,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.EmailConfirmed,
		&i.PasswordHash,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const findUser = `-- name: FindUser :one
SELECT id, created_at, name, email, email_confirmed, password_hash FROM users WHERE id = ?
`

func (q *Queries) FindUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.EmailConfirmed,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, created_at, name, email, email_confirmed, password_hash FROM users WHERE email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.EmailConfirmed,
		&i.PasswordHash,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = ?
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, id)
	var password_hash []byte
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updateEmailConfirmed = `-- name: UpdateEmailConfirmed :execresult
UPDATE users SET email_confirmed = ? WHERE id = ?
`

type UpdateEmailConfirmedParams struct {
	EmailConfirmed bool
	ID             string
}

func (q *Queries) UpdateEmailConfirmed(ctx context.Context, arg UpdateEmailConfirmedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEmailConfirmed, arg.EmailConfirmed, arg.ID)
}

const updateUserName = `-- name: UpdateUserName :execresult
UPDATE users SET name = ? WHERE id = ?
`

type UpdateUserNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserName, arg.Name, arg.ID)
}
