// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createGatewayToken = `-- name: CreateGatewayToken :exec
INSERT INTO gateway_tokens (created_at, user_id, token_hash, expires) VALUES ($1, $2, $3, $4)
`

type CreateGatewayTokenParams struct {
	CreatedAt int64
	UserID    string
	TokenHash []byte
	Expires   int64
}

func (q *Queries) CreateGatewayToken(ctx context.Context, arg CreateGatewayTokenParams) error {
	_, err := q.db.Exec(ctx, createGatewayToken,
		arg.CreatedAt,
		arg.UserID,
		arg.TokenHash,
		arg.Expires,
	)
	return err
}

const deleteGatewayToken = `-- name: DeleteGatewayToken :execresult
DELETE FROM gateway_tokens WHERE token_hash = $1 OR expires < $2
`

type DeleteGatewayTokenParams struct {
	TokenHash []byte
	Now       int64
}

func (q *Queries) DeleteGatewayToken(ctx context.Context, arg DeleteGatewayTokenParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteGatewayToken, arg.TokenHash, arg.Now)
}

const deleteGatewayTokensByUser = `-- name: DeleteGatewayTokensByUser :execresult
DELETE FROM gateway_tokens WHERE user_id = $1 OR expires < $2
`

type DeleteGatewayTokensByUserParams struct {
	UserID string
	Now    int64
}

func (q *Queries) DeleteGatewayTokensByUser(ctx context.Context, arg DeleteGatewayTokensByUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteGatewayTokensByUser, arg.UserID, arg.Now)
}

const findGatewayToken = `-- name: FindGatewayToken :one
SELECT created_at, user_id, token_hash, expires FROM gateway_tokens WHERE token_hash = $1 AND expires > $2
`

type FindGatewayTokenParams struct {
	TokenHash []byte
	Now       int64
}

func (q *Queries) FindGatewayToken(ctx context.Context, arg FindGatewayTokenParams) (GatewayToken, error) {
	row := q.db.QueryRow(ctx, findGatewayToken, arg.TokenHash, arg.Now)
	var i GatewayToken
	err := row.Scan(
		&i.CreatedAt,
		&i.UserID,
		&i.TokenHash,
		&i.Expires,
	)
	return i, err
}
