// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CheckRemember2FAToken(ctx context.Context, arg CheckRemember2FATokenParams) (bool, error)
	CommitSession(ctx context.Context, arg CommitSessionParams) error
	CountRecoveryCodes(ctx context.Context, userID string) (int64, error)
	CreateChangeEmailRequest(ctx context.Context, arg CreateChangeEmailRequestParams) (pgconn.CommandTag, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (Oauth, error)
	CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (pgconn.CommandTag, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error
	CreateRemember2FAToken(ctx context.Context, arg CreateRemember2FATokenParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) (pgconn.CommandTag, error)
	DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) (pgconn.CommandTag, error)
	DeleteOAuthTokenByUser(ctx context.Context, arg DeleteOAuthTokenByUserParams) error
	DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (pgconn.CommandTag, error)
	DeleteRecoveryCode(ctx context.Context, arg DeleteRecoveryCodeParams) (pgconn.CommandTag, error)
	DeleteRecoveryCodes(ctx context.Context, userID string) (pgconn.CommandTag, error)
	DeleteRemember2FAToken(ctx context.Context, arg DeleteRemember2FATokenParams) (pgconn.CommandTag, error)
	DeleteRemember2FATokens(ctx context.Context, arg DeleteRemember2FATokensParams) (pgconn.CommandTag, error)
	DeleteSession(ctx context.Context, token string) error
	DeleteToken(ctx context.Context, arg DeleteTokenParams) (pgconn.CommandTag, error)
	DeleteUser(ctx context.Context, id string) (pgconn.CommandTag, error)
	FindClient(ctx context.Context, id string) (Client, error)
	FindClientByUser(ctx context.Context, userID string) ([]Client, error)
	FindClientByUserAndID(ctx context.Context, arg FindClientByUserAndIDParams) (Client, error)
	FindOAuthPermissions(ctx context.Context, arg FindOAuthPermissionsParams) (Permission, error)
	FindOAuthToken(ctx context.Context, arg FindOAuthTokenParams) (Oauth, error)
	FindPasskey(ctx context.Context, arg FindPasskeyParams) (Passkey, error)
	FindPasskeys(ctx context.Context, userID string) ([]Passkey, error)
	FindSession(ctx context.Context, arg FindSessionParams) ([]byte, error)
	FindSessions(ctx context.Context, now int64) ([]FindSessionsRow, error)
	FindToken(ctx context.Context, arg FindTokenParams) (Token, error)
	FindTokenByValue(ctx context.Context, arg FindTokenByValueParams) (Token, error)
	FindUser(ctx context.Context, id string) (User, error)
	FindUserByChangeEmailToken(ctx context.Context, arg FindUserByChangeEmailTokenParams) (User, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUsers(ctx context.Context) ([]User, error)
	GetJWTKeys(ctx context.Context) (RsaKey, error)
	GetOTP(ctx context.Context, id string) (GetOTPRow, error)
	GetUserPasswordHash(ctx context.Context, id string) ([]byte, error)
	InsertJWTKeys(ctx context.Context, arg InsertJWTKeysParams) error
	RevokeOAuthPermissions(ctx context.Context, arg RevokeOAuthPermissionsParams) (pgconn.CommandTag, error)
	SetOAuthPermissions(ctx context.Context, arg SetOAuthPermissionsParams) (Permission, error)
	SetOTPActive(ctx context.Context, arg SetOTPActiveParams) (pgconn.CommandTag, error)
	UpdateAdminStatus(ctx context.Context, arg UpdateAdminStatusParams) (pgconn.CommandTag, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) (pgconn.CommandTag, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (string, error)
	UpdateEmailConfirmed(ctx context.Context, arg UpdateEmailConfirmedParams) (pgconn.CommandTag, error)
	UpdateOTP(ctx context.Context, arg UpdateOTPParams) (pgconn.CommandTag, error)
	UpdatePasskey(ctx context.Context, arg UpdatePasskeyParams) (pgconn.CommandTag, error)
	UpdatePasskeyCredential(ctx context.Context, arg UpdatePasskeyCredentialParams) (pgconn.CommandTag, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (pgconn.CommandTag, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (pgconn.CommandTag, error)
	UseOAuthToken(ctx context.Context, arg UseOAuthTokenParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
